#version: '3.8'

services:
  db:
    image: postgres:13
    container_name: car_insurance_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ravi123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-insurance-application
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ravi123

volumes:
  postgres_data: